### ISSUE TITLE
epic: decouple explorer from SDK

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer#2483]
With the objective of generating independent release cycles and to foster easier modifications of Decentraland, some components should be separated into their own repositories. I believe this would lower the entry barrier for new contributors and also make the code structure less scary and easier to understand.

Also, having separated repositories means some hard interfaces should be set in place, those interfaces will help establish long-term backwards compatible protocols and components.

## Technical definitions of interfaces
- [ ] Website<>Kernel protocol (WIP)
- [ ] Kernel<>Renderer protocol https://github.com/decentraland/renderer-protocol
- [ ] Runtime<>User generated code protocol https://github.com/decentraland/posix

## Tasks
- [ ] Separate website in its own repo https://github.com/decentraland/explorer-website
- [ ] Separate unity-renderer in its own repository https://github.com/decentraland/unity-renderer/
- [ ] Separate build-ecs in its own repository https://github.com/decentraland/js-sdk-toolchain/tree/main/packages/%40dcl/build-ecs
- [ ] Separate dcl-amd in its own repository https://github.com/decentraland/js-sdk-toolchain/tree/main/packages/%40dcl/amd
- [ ] Separate decentraland-ecs in its own repository https://github.com/decentraland/js-sdk-toolchain/tree/main/packages/decentraland-ecs
